/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignUpSplatRouteImport } from './routes/sign-up.$'
import { Route as SignInSplatRouteImport } from './routes/sign-in.$'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as AppWalletRouteImport } from './routes/_app.wallet'
import { Route as AppStudioRouteImport } from './routes/_app.studio'
import { Route as AppMarketplaceRouteImport } from './routes/_app.marketplace'
import { Route as ApiWalletIndexRouteImport } from './routes/api/wallet/index'
import { Route as ApiWalletNanopaymentRouteImport } from './routes/api/wallet/nanopayment'
import { Route as ApiWalletAppKitRouteImport } from './routes/api/wallet/app-kit'
import { Route as ApiMasterStatusRouteImport } from './routes/api/master/status'
import { Route as ApiCronSettleBatchRouteImport } from './routes/api/cron/settle-batch'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpSplatRoute = SignUpSplatRouteImport.update({
  id: '/sign-up/$',
  path: '/sign-up/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInSplatRoute = SignInSplatRouteImport.update({
  id: '/sign-in/$',
  path: '/sign-in/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWalletRoute = AppWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AppRoute,
} as any)
const AppStudioRoute = AppStudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => AppRoute,
} as any)
const AppMarketplaceRoute = AppMarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => AppRoute,
} as any)
const ApiWalletIndexRoute = ApiWalletIndexRouteImport.update({
  id: '/api/wallet/',
  path: '/api/wallet/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWalletNanopaymentRoute = ApiWalletNanopaymentRouteImport.update({
  id: '/api/wallet/nanopayment',
  path: '/api/wallet/nanopayment',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWalletAppKitRoute = ApiWalletAppKitRouteImport.update({
  id: '/api/wallet/app-kit',
  path: '/api/wallet/app-kit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMasterStatusRoute = ApiMasterStatusRouteImport.update({
  id: '/api/master/status',
  path: '/api/master/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronSettleBatchRoute = ApiCronSettleBatchRouteImport.update({
  id: '/api/cron/settle-batch',
  path: '/api/cron/settle-batch',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/marketplace': typeof AppMarketplaceRoute
  '/studio': typeof AppStudioRoute
  '/wallet': typeof AppWalletRoute
  '/api/health': typeof ApiHealthRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/api/cron/settle-batch': typeof ApiCronSettleBatchRoute
  '/api/master/status': typeof ApiMasterStatusRoute
  '/api/wallet/app-kit': typeof ApiWalletAppKitRoute
  '/api/wallet/nanopayment': typeof ApiWalletNanopaymentRoute
  '/api/wallet/': typeof ApiWalletIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/marketplace': typeof AppMarketplaceRoute
  '/studio': typeof AppStudioRoute
  '/wallet': typeof AppWalletRoute
  '/api/health': typeof ApiHealthRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/api/cron/settle-batch': typeof ApiCronSettleBatchRoute
  '/api/master/status': typeof ApiMasterStatusRoute
  '/api/wallet/app-kit': typeof ApiWalletAppKitRoute
  '/api/wallet/nanopayment': typeof ApiWalletNanopaymentRoute
  '/api/wallet': typeof ApiWalletIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/marketplace': typeof AppMarketplaceRoute
  '/_app/studio': typeof AppStudioRoute
  '/_app/wallet': typeof AppWalletRoute
  '/api/health': typeof ApiHealthRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/api/cron/settle-batch': typeof ApiCronSettleBatchRoute
  '/api/master/status': typeof ApiMasterStatusRoute
  '/api/wallet/app-kit': typeof ApiWalletAppKitRoute
  '/api/wallet/nanopayment': typeof ApiWalletNanopaymentRoute
  '/api/wallet/': typeof ApiWalletIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/marketplace'
    | '/studio'
    | '/wallet'
    | '/api/health'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/api/cron/settle-batch'
    | '/api/master/status'
    | '/api/wallet/app-kit'
    | '/api/wallet/nanopayment'
    | '/api/wallet/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/marketplace'
    | '/studio'
    | '/wallet'
    | '/api/health'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/api/cron/settle-batch'
    | '/api/master/status'
    | '/api/wallet/app-kit'
    | '/api/wallet/nanopayment'
    | '/api/wallet'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/marketplace'
    | '/_app/studio'
    | '/_app/wallet'
    | '/api/health'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/api/cron/settle-batch'
    | '/api/master/status'
    | '/api/wallet/app-kit'
    | '/api/wallet/nanopayment'
    | '/api/wallet/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ApiHealthRoute: typeof ApiHealthRoute
  SignInSplatRoute: typeof SignInSplatRoute
  SignUpSplatRoute: typeof SignUpSplatRoute
  ApiCronSettleBatchRoute: typeof ApiCronSettleBatchRoute
  ApiMasterStatusRoute: typeof ApiMasterStatusRoute
  ApiWalletAppKitRoute: typeof ApiWalletAppKitRoute
  ApiWalletNanopaymentRoute: typeof ApiWalletNanopaymentRoute
  ApiWalletIndexRoute: typeof ApiWalletIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up/$': {
      id: '/sign-up/$'
      path: '/sign-up/$'
      fullPath: '/sign-up/$'
      preLoaderRoute: typeof SignUpSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in/$': {
      id: '/sign-in/$'
      path: '/sign-in/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof SignInSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/wallet': {
      id: '/_app/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof AppWalletRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/studio': {
      id: '/_app/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof AppStudioRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/marketplace': {
      id: '/_app/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof AppMarketplaceRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/wallet/': {
      id: '/api/wallet/'
      path: '/api/wallet'
      fullPath: '/api/wallet/'
      preLoaderRoute: typeof ApiWalletIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/wallet/nanopayment': {
      id: '/api/wallet/nanopayment'
      path: '/api/wallet/nanopayment'
      fullPath: '/api/wallet/nanopayment'
      preLoaderRoute: typeof ApiWalletNanopaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/wallet/app-kit': {
      id: '/api/wallet/app-kit'
      path: '/api/wallet/app-kit'
      fullPath: '/api/wallet/app-kit'
      preLoaderRoute: typeof ApiWalletAppKitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/master/status': {
      id: '/api/master/status'
      path: '/api/master/status'
      fullPath: '/api/master/status'
      preLoaderRoute: typeof ApiMasterStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/settle-batch': {
      id: '/api/cron/settle-batch'
      path: '/api/cron/settle-batch'
      fullPath: '/api/cron/settle-batch'
      preLoaderRoute: typeof ApiCronSettleBatchRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppMarketplaceRoute: typeof AppMarketplaceRoute
  AppStudioRoute: typeof AppStudioRoute
  AppWalletRoute: typeof AppWalletRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppMarketplaceRoute: AppMarketplaceRoute,
  AppStudioRoute: AppStudioRoute,
  AppWalletRoute: AppWalletRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ApiHealthRoute: ApiHealthRoute,
  SignInSplatRoute: SignInSplatRoute,
  SignUpSplatRoute: SignUpSplatRoute,
  ApiCronSettleBatchRoute: ApiCronSettleBatchRoute,
  ApiMasterStatusRoute: ApiMasterStatusRoute,
  ApiWalletAppKitRoute: ApiWalletAppKitRoute,
  ApiWalletNanopaymentRoute: ApiWalletNanopaymentRoute,
  ApiWalletIndexRoute: ApiWalletIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
