/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppWalletRouteImport } from './routes/_app.wallet'
import { Route as AppStudioRouteImport } from './routes/_app.studio'
import { Route as ApiWalletIndexRouteImport } from './routes/api/wallet/index'
import { Route as ApiWalletNanopaymentRouteImport } from './routes/api/wallet/nanopayment'
import { Route as ApiMasterStatusRouteImport } from './routes/api/master/status'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppWalletRoute = AppWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AppRoute,
} as any)
const AppStudioRoute = AppStudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => AppRoute,
} as any)
const ApiWalletIndexRoute = ApiWalletIndexRouteImport.update({
  id: '/api/wallet/',
  path: '/api/wallet/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWalletNanopaymentRoute = ApiWalletNanopaymentRouteImport.update({
  id: '/api/wallet/nanopayment',
  path: '/api/wallet/nanopayment',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMasterStatusRoute = ApiMasterStatusRouteImport.update({
  id: '/api/master/status',
  path: '/api/master/status',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/studio': typeof AppStudioRoute
  '/wallet': typeof AppWalletRoute
  '/api/master/status': typeof ApiMasterStatusRoute
  '/api/wallet/nanopayment': typeof ApiWalletNanopaymentRoute
  '/api/wallet/': typeof ApiWalletIndexRoute
}
export interface FileRoutesByTo {
  '/studio': typeof AppStudioRoute
  '/wallet': typeof AppWalletRoute
  '/': typeof AppIndexRoute
  '/api/master/status': typeof ApiMasterStatusRoute
  '/api/wallet/nanopayment': typeof ApiWalletNanopaymentRoute
  '/api/wallet': typeof ApiWalletIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/studio': typeof AppStudioRoute
  '/_app/wallet': typeof AppWalletRoute
  '/_app/': typeof AppIndexRoute
  '/api/master/status': typeof ApiMasterStatusRoute
  '/api/wallet/nanopayment': typeof ApiWalletNanopaymentRoute
  '/api/wallet/': typeof ApiWalletIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/studio'
    | '/wallet'
    | '/api/master/status'
    | '/api/wallet/nanopayment'
    | '/api/wallet/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/studio'
    | '/wallet'
    | '/'
    | '/api/master/status'
    | '/api/wallet/nanopayment'
    | '/api/wallet'
  id:
    | '__root__'
    | '/_app'
    | '/_app/studio'
    | '/_app/wallet'
    | '/_app/'
    | '/api/master/status'
    | '/api/wallet/nanopayment'
    | '/api/wallet/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  ApiMasterStatusRoute: typeof ApiMasterStatusRoute
  ApiWalletNanopaymentRoute: typeof ApiWalletNanopaymentRoute
  ApiWalletIndexRoute: typeof ApiWalletIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/wallet': {
      id: '/_app/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof AppWalletRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/studio': {
      id: '/_app/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof AppStudioRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/wallet/': {
      id: '/api/wallet/'
      path: '/api/wallet'
      fullPath: '/api/wallet/'
      preLoaderRoute: typeof ApiWalletIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/wallet/nanopayment': {
      id: '/api/wallet/nanopayment'
      path: '/api/wallet/nanopayment'
      fullPath: '/api/wallet/nanopayment'
      preLoaderRoute: typeof ApiWalletNanopaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/master/status': {
      id: '/api/master/status'
      path: '/api/master/status'
      fullPath: '/api/master/status'
      preLoaderRoute: typeof ApiMasterStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppStudioRoute: typeof AppStudioRoute
  AppWalletRoute: typeof AppWalletRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppStudioRoute: AppStudioRoute,
  AppWalletRoute: AppWalletRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  ApiMasterStatusRoute: ApiMasterStatusRoute,
  ApiWalletNanopaymentRoute: ApiWalletNanopaymentRoute,
  ApiWalletIndexRoute: ApiWalletIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
